version: "3"

services:
  app:
    build: .
    container_name: smart-sr_app
    ports:
      - "8081:8080"
    volumes:
      - .:/go/src/smart-sr
    environment:
      GO_ENV: docker
    command: go run cmd/smart-sr/main.go
  db:
    image: mysql:latest
    container_name: smart-sr_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: smart-sr
      MYSQL_PASSWORD: smart-sr
      MYSQL_DATABASE: smart-sr
